---
sidebar: sidebar 
permalink: reference_default_configs.html 
keywords: linux, user name, operating system, installation files, installation folder, folder, log, logs, service, mysql, packages, linux,  svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Details zur Konfiguration von Cloud Manager und Cloud Volumes ONTAP können Ihnen bei der Administration der Systeme helfen. 
translate: false 
---
= Standardkonfigurationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Details zur Konfiguration von Cloud Manager und Cloud Volumes ONTAP können Ihnen bei der Administration der Systeme helfen.



== Standardkonfiguration für Cloud Manager unter Linux

Wenn Sie eine Fehlerbehebung für Cloud Manager oder Ihren Linux-Host durchführen müssen, kann dies dazu beitragen, die Konfiguration von Cloud Manager zu verstehen.

* Wenn Sie Cloud Manager von NetApp Cloud Central (oder direkt aus dem Marketplace eines Cloud-Providers) implementiert haben, beachten Sie Folgendes:
+
** In AWS lautet der Benutzername für die EC2 Linux-Instanz ec2-user.
** Das Betriebssystem für das Cloud Manager Image ist Red hat Enterprise Linux 7.4 (HVM).
+
Das Betriebssystem enthält keine GUI. Sie müssen ein Terminal verwenden, um auf das System zuzugreifen.



* Der Installationsordner von Cloud Manager befindet sich am folgenden Speicherort:
+
/opt/application/netapp/cloudmanager

* Protokolldateien befinden sich im folgenden Ordner:
+
/opt/application/netapp/cloudmanager/log

* Der Cloud Manager Service heißt occm.
* Der occm-Dienst ist vom MySQL-Dienst abhängig.
+
Wenn der MySQL-Dienst nicht verfügbar ist, ist auch der occm-Dienst nicht verfügbar.

* Cloud Manager installiert die folgenden Pakete auf dem Linux-Host, sofern sie noch nicht installiert sind:
+
** 7-Zip
** AWSCLI
** Java
** Kubectl
** MySQL
** Tridentctl
** Wget






== Standardkonfiguration für Cloud Volumes ONTAP

Wenn Sie verstehen, wie Cloud Volumes ONTAP standardmäßig konfiguriert ist, können Sie Ihre Systeme einrichten und verwalten. Dies gilt insbesondere, wenn Sie mit ONTAP vertraut sind, da sich das Standard-Setup für Cloud Volumes ONTAP von ONTAP unterscheidet.

* Cloud Volumes ONTAP ist als Single-Node-System in AWS, Azure und GCP verfügbar und als HA-Paar in AWS und Azure.
* Cloud Manager erstellt bei der Implementierung von Cloud Volumes ONTAP eine Data Serving SVM. Die Verwendung mehrerer Datenservice-SVMs wird nicht unterstützt.
* Cloud Manager installiert die folgenden ONTAP Funktionslizenzen automatisch auf Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** ISCSI
** NetApp Volume Encryption (nur für BYOL oder registrierte PAYGO Systeme)
** NFS
** SnapMirror
** SnapRestore
** SnapVault


* Standardmäßig werden mehrere Netzwerkschnittstellen erstellt:
+
** Eine Cluster Management-LIF
** Eine Intercluster-LIF
** SVM-Management-LIF auf HA-Systemen in Azure, Single-Node-Systeme in AWS und optional auf HA-Systemen in mehreren AWS Availability Zones
** Eine Node Management-LIF
** Eine iSCSI-Daten-LIF
** Eine CIFS- und NFS-Daten-LIF
+

NOTE: Aufgrund der EC2-Anforderungen ist das LIF-Failover für Cloud Volumes ONTAP standardmäßig deaktiviert. Durch die Migration einer LIF auf einen anderen Port wird die externe Zuordnung zwischen IP-Adressen und Netzwerkschnittstellen in der Instanz aufgehoben, sodass der LIF nicht mehr zugänglich ist.



* Cloud Volumes ONTAP sendet Konfigurations-Backups über HTTPS an Cloud Manager.
+
Wenn Sie sich bei Cloud Manager anmelden, können Sie über die Backup-Daten darauf zugreifen https://ipaddress/occm/offboxconfig/[]

* Cloud Manager legt einige Volume-Attribute anders fest als andere Management-Tools (z. B. System Manager oder CLI).
+
In der folgenden Tabelle sind die Volume-Attribute aufgeführt, die Cloud Manager anders als die Standardeinstellungen festlegt:

+
[cols="15,85"]
|===
| Attribut | Vom Cloud Manager festgelegter Wert 


| AutoSize Modus | Wachsen 


| Maximale automatische Größe  a| 
1.000 Prozent


NOTE: Der Kontoadministrator kann diesen Wert auf der Seite Einstellungen ändern.



| Sicherheitsstil | NTFS für CIFS-Volumes UNIX für NFS-Volumes 


| Platz garantiert Stil | Keine 


| UNIX-Berechtigungen (nur NFS) | 777 
|===
+
Informationen zu diesen Attributen finden Sie auf der Seite „_Volume create_ man“.





== Boot- und Root-Daten für Cloud Volumes ONTAP

Zusätzlich zum Storage für Benutzerdaten erwirbt Cloud Manager auch Cloud Storage für Boot- und Root-Daten auf jedem Cloud Volumes ONTAP System.



=== AWS

* Zwei universell einsetzbare SSD-Festplatten:
+
** Eine 140-GB-Festplatte für Stammdaten (eine pro Node)
** 9.6 oder höher: Eine 86-GB-Festplatte für Boot-Daten (eine pro Node)
** 9.5 und früher: Eine 45-GB-Festplatte für Boot-Daten (eine pro Node)


* Ein EBS-Snapshot für jede Boot- und Root-Festplatte
* Bei HA-Paaren ist ein EBS-Volume für die Mediator-Instanz, das ca. 8 GB beträgt




=== Azure (Single Node)

* Zwei Premium-SSD-Festplatten:
+
** Eine 90-GB-Festplatte für Boot-Daten
** Eine 140-GB-Festplatte für Stammdaten


* Ein Azure Snapshot für jedes Boot- und Root-Laufwerk




=== Azure (HA-Paare)

* Zwei 90-GB-Premium-SSD-Laufwerke für das Boot-Volume (eine pro Node)
* Zwei Blobs für 140 GB Premium-Storage für das Root-Volume (eine pro Node)
* Zwei 128-GB-Standard-HDD-Festplatten zum Speichern der Cores (eine pro Node)
* Ein Azure Snapshot für jedes Boot- und Root-Laufwerk




=== GCP

* Eine persistente 10-GB-Standardfestplatte für Boot-Daten
* Eine persistente 64-GB-Standardfestplatte für Stammdaten
* Eine persistente 500-GB-Standardfestplatte für NVRAM
* Eine persistente 216-GB-Standardfestplatte zum Speichern der Kerne
* Je ein GCP-Snapshot für die Boot-Festplatte und die Root-Festplatte




=== Wo sich die Festplatten befinden

Cloud Manager legt den Storage wie folgt vor:

* Boot-Daten befinden sich auf einem Laufwerk, das mit der Instanz oder Virtual Machine verbunden ist.
+
Diese Festplatte, die das Boot-Image enthält, steht Cloud Volumes ONTAP nicht zur Verfügung.

* Die Stammdaten, die die Systemkonfiguration und die Protokolle enthalten, befinden sich in aggr0.
* Das Root-Volume der Storage Virtual Machine (SVM) befindet sich in aggr1.
* Daten-Volumes befinden sich auch in aggr1.




=== Verschlüsselung

Boot- und Root-Festplatten sind in Azure und Google Cloud Platform immer verschlüsselt, da bei diesen Cloud-Providern die Verschlüsselung standardmäßig aktiviert ist.

Wenn Sie die Datenverschlüsselung in AWS mithilfe des KMS (Key Management Service) aktivieren, werden sowohl Boot- als auch Root-Festplatten für Cloud Volumes ONTAP verschlüsselt. Dazu gehört die Boot-Festplatte für die Instanz des Mediators in einem HA-Paar. Die Laufwerke werden über das CMK verschlüsselt, das Sie bei der Erstellung der Arbeitsumgebung auswählen.
