---
sidebar: sidebar 
permalink: task_planning_your_config.html 
keywords: license, disk, ebs, storage, size, write speed, volume usage, explore, standard, premium, byol, ec2, capacity, limit, configurations, virtual machine, vm, regions, supported disks, disk types, general purpose, gp2 provisioned IOPS, piops, throughput optimized, cold, SSD, HDD, st1, sc1, premium storage, standard storage, use profile, thin provisioning, deduplication, compression, Cloud Volumes ONTAP explore, Cloud Volumes ONTAP standard, Cloud Volumes ONTAP premium, Cloud Volumes ONTAP byol, shared instance, dedicated instance, write speed, high write speed, normal write speed, network information, worksheet, limit, limits, storage limits, volume limit, aggregate limit, maximum volume size, maximum aggregate size 
summary: Wenn Sie Cloud Volumes ONTAP implementieren, können Sie ein vorkonfiguriertes System auswählen, das Ihren Workload-Anforderungen entspricht, oder Sie können eine eigene Konfiguration erstellen. Wenn Sie sich für eine eigene Konfiguration entscheiden, sollten Sie sich mit den verfügbaren Optionen vertraut machen. 
---
= Planung Ihrer Cloud Volumes ONTAP Konfiguration
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Wenn Sie Cloud Volumes ONTAP implementieren, können Sie ein vorkonfiguriertes System auswählen, das Ihren Workload-Anforderungen entspricht, oder Sie können eine eigene Konfiguration erstellen. Wenn Sie sich für eine eigene Konfiguration entscheiden, sollten Sie sich mit den verfügbaren Optionen vertraut machen.



== Auswahl eines Lizenztyps

Cloud Volumes ONTAP ist in zwei Preisoptionen erhältlich: Nutzungsbasiert und als BYOL-Modell (Bring-Your-Own-License). Für Pay-as-you-go können Sie zwischen drei Lizenzen wählen: Explore, Standard oder Premium. Jede Lizenz bietet verschiedene Kapazitäts- und Computing-Optionen.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_aws_97.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP 9.7 in AWS"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_azure_97.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP 9.7 in Azure"^]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_configs_gcp_97.html["Unterstützte Konfigurationen für Cloud Volumes ONTAP 9.7 in GCP"^]




== Storage-Grenzen kennen

Die Rohkapazitätsgrenze für ein Cloud Volumes ONTAP System ist an die Lizenz gebunden. Zusätzliche Beschränkungen wirken sich auf die Größe von Aggregaten und Volumes aus. Sie sollten sich dieser Grenzen bei der Planung Ihrer Konfiguration bewusst sein.

* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_aws_97.html["Storage-Limits für Cloud Volumes ONTAP 9.7 in AWS"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_azure_97.html["Storage-Höchstwerte für Cloud Volumes ONTAP 9.7 in Azure"]
* https://docs.netapp.com/us-en/cloud-volumes-ontap/reference_limits_gcp_97.html["Storage-Grenzen für Cloud Volumes ONTAP 9.7 in GCP"]




== Auswählen einer Schreibgeschwindigkeit

Mit Cloud Manager können Sie eine Einstellung für die Schreibgeschwindigkeit für Cloud Volumes ONTAP Systeme mit einem Node wählen. Bevor Sie sich für eine Schreibgeschwindigkeit entscheiden, sollten Sie die Unterschiede zwischen den normalen und hohen Einstellungen sowie Risiken und Empfehlungen verstehen, wenn Sie eine hohe Schreibgeschwindigkeit verwenden.



==== Unterschied zwischen normaler Schreibgeschwindigkeit und hoher Schreibgeschwindigkeit

Wenn Sie sich für eine normale Schreibgeschwindigkeit entscheiden, werden die Daten direkt auf die Festplatte geschrieben, wodurch die Wahrscheinlichkeit eines Datenverlusts bei einem ungeplanten Systemausfall verringert wird.

Wenn Sie hohe Schreibgeschwindigkeit wählen, werden die Daten vor dem Schreiben auf die Festplatte im Speicher gepuffert, was eine schnellere Schreibleistung ermöglicht. Aufgrund dieses Cachings besteht die Gefahr eines Datenverlusts, wenn ein ungeplanter Systemausfall auftritt.

Die Datenmenge, die bei einem ungeplanten Systemausfall verloren gehen kann, entspricht der Spanne der letzten beiden Konsistenzpunkte. Ein Konsistenzpunkt ist das Schreiben gepufferter Daten auf die Festplatte. Ein Konsistenzpunkt tritt auf, wenn das Schreibprotokoll voll ist oder nach 10 Sekunden (je nachdem, was zuerst eintritt). Die Performance des AWS EBS-Volumes kann sich jedoch auf die Verarbeitungszeit des Konsistenzpunkts auswirken.



==== Wann wird hohe Schreibgeschwindigkeit verwendet

Hohe Schreibgeschwindigkeit ist eine gute Wahl, wenn für Ihre Workload eine schnelle Schreibleistung erforderlich ist und Sie das Risiko eines Datenverlusts bei einem ungeplanten Systemausfall überstehen können.



==== Empfehlungen bei hoher Schreibgeschwindigkeit

Wenn Sie die hohe Schreibgeschwindigkeit aktivieren, sollten Sie den Schreibschutz auf der Anwendungsebene sicherstellen.



== Auswählen eines Volume-Nutzungsprofils

ONTAP umfasst mehrere Storage-Effizienzfunktionen, mit denen Sie die benötigte Storage-Gesamtmenge reduzieren können. Wenn Sie ein Volume in Cloud Manager erstellen, können Sie ein Profil auswählen, das diese Funktionen aktiviert, oder ein Profil, das sie deaktiviert. Sie sollten mehr über diese Funktionen erfahren, um zu entscheiden, welches Profil Sie verwenden möchten.

NetApp Storage-Effizienzfunktionen bieten folgende Vorteile:

Thin Provisioning:: Bietet Hosts oder Benutzern mehr logischen Storage als in Ihrem physischen Storage-Pool. Anstatt Storage vorab zuzuweisen, wird jedem Volume beim Schreiben von Daten dynamisch Speicherplatz zugewiesen.
Deduplizierung:: Verbessert die Effizienz, indem identische Datenblöcke lokalisiert und durch Verweise auf einen einzelnen gemeinsam genutzten Block ersetzt werden. Durch diese Technik werden die Storage-Kapazitätsanforderungen reduziert, da redundante Datenblöcke im selben Volume eliminiert werden.
Komprimierung:: Reduziert die physische Kapazität, die zum Speichern von Daten erforderlich ist, indem Daten in einem Volume auf primärem, sekundärem und Archiv-Storage komprimiert werden.




== AWS Planung

Planen Sie die Implementierung von Cloud Volumes ONTAP in AWS, indem Sie die Größe Ihres Systems dimensionieren und die erforderlichen Netzwerkinformationen überprüfen.

* <<Dimensionierung Ihres Systems in AWS>>
* <<Arbeitsblatt mit Informationen zum AWS-Netzwerk>>




=== Dimensionierung Ihres Systems in AWS

Mit der Dimensionierung Ihres Cloud Volumes ONTAP Systems können Sie die Anforderungen an Performance und Kapazität erfüllen. Bei der Auswahl eines Instanztyps, des Festplattentyp und der Festplattengröße sollten Sie einige wichtige Punkte beachten:

Instanztyp::
+
--
* Stimmen Sie die Workload-Anforderungen dem maximalen Durchsatz und IOPS für jeden EC2-Instanztyp ab.
* Wenn mehrere Benutzer gleichzeitig auf das System schreiben, wählen Sie einen Instanztyp aus, der über genügend CPUs verfügt, um die Anforderungen zu verwalten.
* Wenn Sie eine Anwendung haben, die hauptsächlich liest, dann wählen Sie ein System mit genügend RAM.
+
** https://aws.amazon.com/ec2/instance-types/["AWS Dokumentation: Amazon EC2 Instanztypen"^]
** https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html["AWS Dokumentation: Für Amazon EBS optimierte Instanzen"^]




--
EBS-Festplattentyp:: Allgemeine SSDs sind der am häufigsten verwendete Festplattentyp für Cloud Volumes ONTAP. Weitere Informationen zu den Anwendungsfällen für EBS-Festplatten finden Sie unter http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS Dokumentation: EBS Volume-Typen"^].
EBS-Festplattengröße:: Sie müssen beim Start eines Cloud Volumes ONTAP Systems die ursprüngliche Festplattengröße auswählen. Danach können Sie link:concept_storage_management.html["Cloud Manager managt die Kapazität eines Systems für Sie"], Aber wenn Sie wollen link:task_provisioning_storage.html#creating-aggregates["Erstellen Sie Aggregate selbst"], Verachten Sie auf folgende Punkte:
+
--
* Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.
* Die Performance von EBS-Festplatten ist an die Festplattengröße gebunden. Die Größe bestimmt die IOPS-Basiswerte und die maximale Burst-Dauer für SSD-Festplatten sowie den Baseline- und Burst-Durchsatz für HDD-Festplatten.
* Am Ende sollten Sie die Festplattengröße wählen, die Ihnen die _dauerhafte Performance_ bietet, die Sie benötigen.
* Selbst wenn Sie größere Festplatten wählen (z. B. sechs 4-TB-Festplatten), erhalten Sie möglicherweise nicht alle IOPS, da die EC2-Instanz ihr Bandbreitenlimit erreichen kann.
+
Weitere Informationen zur Performance der EBS Festplatten finden Sie in http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html["AWS Dokumentation: EBS Volume-Typen"^].



--


Sehen Sie sich das folgende Video an, um weitere Informationen zur Dimensionierung Ihres Cloud Volumes ONTAP-Systems in AWS zu erhalten:

video::GELcXmOuYPw[youtube,width=848,height=480]


=== Arbeitsblatt mit Informationen zum AWS-Netzwerk

Wenn Sie Cloud Volumes ONTAP in AWS starten, müssen Sie Details zu Ihrem VPC-Netzwerk angeben. Sie können ein Arbeitsblatt verwenden, um die Informationen von Ihrem Administrator zu sammeln.



==== Netzwerkinformationen für Cloud Volumes ONTAP

[cols="30,70"]
|===
| AWS-Informationen | Ihr Wert 


| Region |  


| VPC |  


| Subnetz |  


| Sicherheitsgruppe (wenn Sie Ihre eigene verwenden) |  
|===


==== Netzwerkinformationen für ein HA-Paar in mehreren AZS

[cols="30,70"]
|===
| AWS-Informationen | Ihr Wert 


| Region |  


| VPC |  


| Sicherheitsgruppe (wenn Sie Ihre eigene verwenden) |  


| Verfügbarkeitszone von Node 1 |  


| Subnetz von Node 1 |  


| Verfügbarkeitszone von Node 2 |  


| Subnetz von Node 2 |  


| Mediator Verfügbarkeitszone |  


| Mediator Subnetz |  


| Schlüsselpaar für den Vermittler |  


| Floating-IP-Adresse für Cluster-Management-Port |  


| Unverankerte IP-Adresse für Daten auf Node 1 |  


| Unverankerte IP-Adresse für Daten auf Node 2 |  


| Routing-Tabellen für unverankerte IP-Adressen |  
|===


== Azure Planung

Planen Sie die Implementierung von Cloud Volumes ONTAP in Azure, indem Sie die Größe Ihres Systems dimensionieren und die erforderlichen Netzwerkinformationen überprüfen.

* <<Dimensionierung Ihres Systems in Azure>>
* <<Azure Network Information Worksheet>>




=== Dimensionierung Ihres Systems in Azure

Mit der Dimensionierung Ihres Cloud Volumes ONTAP Systems können Sie die Anforderungen an Performance und Kapazität erfüllen. Bei der Auswahl von VM-Typ, Festplattentyp und Festplattengröße sind einige wichtige Punkte zu beachten:

Typ der virtuellen Maschine:: Sehen Sie sich die unterstützten Typen von Virtual Machines in an http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Versionshinweise zu Cloud Volumes ONTAP"^] Und überprüfen Sie anschließend Details zu jedem unterstützten VM-Typ. Beachten Sie, dass jeder VM-Typ eine bestimmte Anzahl an Datenfestplatten unterstützt.
+
--
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-general#dsv2-series["Azure-Dokumentation: Allgemeine Größe virtueller Maschinen"^]
* https://docs.microsoft.com/en-us/azure/virtual-machines/linux/sizes-memory#dsv2-series-11-15["Azure-Dokumentation: Für den Speicher optimierte Größen virtueller Maschinen"^]


--
Azure-Festplattentyp:: Wenn Sie Volumes für Cloud Volumes ONTAP erstellen, müssen Sie den zugrunde liegenden Cloud-Storage auswählen, den Cloud Volumes ONTAP als Festplatte verwendet.
+
--
HA-Systeme verwenden Premium-Blobs auf Seite. In der Zwischenzeit können Systeme mit einem Node zwei Typen von Azure Managed Disks nutzen:

* _Premium SSD Managed Disks_ bieten hohe Performance für I/O-intensive Workloads zu höheren Kosten.
* _Standard SSD Managed Disks_ bieten konsistente Performance für Workloads, die niedrige IOPS erfordern.
* _Standard HDD Managed Disks_ sind eine gute Wahl, wenn Sie keine hohen IOPS benötigen und Ihre Kosten senken möchten.
+
Weitere Details zu den Anwendungsfällen für diese Festplatten finden Sie unter https://azure.microsoft.com/documentation/articles/storage-introduction/["Microsoft Azure-Dokumentation: Einführung in Microsoft Azure Storage"^].



--
Festplattengröße Azure:: Wenn Sie Cloud Volumes ONTAP Instanzen starten, müssen Sie die standardmäßige Festplattengröße für Aggregate auswählen. Cloud Manager verwendet diese Festplattengröße für das anfängliche Aggregat und für alle zusätzlichen Aggregate, die es erstellt, wenn Sie die einfache Bereitstellungsoption verwenden. Sie können Aggregate erstellen, die eine Festplattengröße verwenden, die sich von der Standardgröße unterscheidet link:task_provisioning_storage.html#creating-aggregates["Verwenden der erweiterten Zuweisungsoption"].
+
--

TIP: Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.

Bei der Auswahl der Festplattengröße sollten Sie mehrere Faktoren berücksichtigen. Die Festplattengröße wirkt sich darauf aus, wie viel Sie für Storage zahlen, wie viele Volumes Sie in einem Aggregat erstellen können, wie viel Kapazität insgesamt für Cloud Volumes ONTAP zur Verfügung steht und wie hoch die Storage-Performance ist.

Die Performance von Azure Premium Storage ist an die Festplattengröße gebunden. Größere Festplatten bieten höhere IOPS und einen höheren Durchsatz. Beispielsweise kann die Auswahl von 1-TB-Festplatten eine bessere Performance bieten als 500-GB-Festplatten zu höheren Kosten.

Es gibt keine Performance-Unterschiede zwischen den Festplattengrößen für Standard-Storage. Sie sollten die Festplattengröße basierend auf der benötigten Kapazität auswählen.

Unter Azure finden Sie IOPS und Durchsatz nach Festplattengröße:

* https://azure.microsoft.com/en-us/pricing/details/managed-disks/["Microsoft Azure: Preisgestaltung für Managed Disks"^]
* https://azure.microsoft.com/en-us/pricing/details/storage/page-blobs/["Microsoft Azure: Page Blobs Pricing"^]


--




=== Azure Network Information Worksheet

Wenn Sie Cloud Volumes ONTAP in Azure implementieren, müssen Sie Details zu Ihrem virtuellen Netzwerk angeben. Sie können ein Arbeitsblatt verwenden, um die Informationen von Ihrem Administrator zu sammeln.

[cols="30,70"]
|===
| Azure Informationen | Ihr Wert 


| Region |  


| Virtuelles Netzwerk (VNet) |  


| Subnetz |  


| Netzwerksicherheitsgruppe (wenn Sie Ihre eigene verwenden) |  
|===


== GCP-Planung

Planen Sie die Implementierung von Cloud Volumes ONTAP in der Google Cloud Platform, indem Sie die Größe Ihres Systems dimensionieren und die erforderlichen Netzwerkinformationen überprüfen.

* <<Dimensionierung Ihres Systems in GCP>>
* <<Informationarbeitsblatt für das GCP-Netzwerk>>




=== Dimensionierung Ihres Systems in GCP

Mit der Dimensionierung Ihres Cloud Volumes ONTAP Systems können Sie die Anforderungen an Performance und Kapazität erfüllen. Bei der Auswahl von Maschinentyp, Festplattentyp und Festplattengröße sind einige wichtige Punkte zu beachten:

Maschinentyp:: Sehen Sie sich die unterstützten Maschinentypen im an http://docs.netapp.com/cloud-volumes-ontap/us-en/index.html["Versionshinweise zu Cloud Volumes ONTAP"^] Und dann lesen Sie die Details von Google zu jedem unterstützten Maschinentyp durch. Passen Sie Ihre Workload-Anforderungen an die Anzahl an vCPUs und Speicher für den Maschinentyp an. Beachten Sie, dass jeder CPU-Kern die Netzwerk-Performance steigert.
+
--
Weitere Informationen finden Sie im Folgenden:

* https://cloud.google.com/compute/docs/machine-types#n1_machine_types["Google Cloud-Dokumentation: N1 Standard-Maschinentypen"^]
* https://cloud.google.com/docs/compare/data-centers/networking#performance["Google Cloud Dokumentation: Performance"^]


--
GCP-Festplattentyp:: Bei der Erstellung von Volumes für Cloud Volumes ONTAP müssen Sie den zugrunde liegenden Cloud-Storage auswählen, den Cloud Volumes ONTAP für eine Festplatte verwendet. Der Festplattentyp kann entweder _Zonal SSD Persistent Disks_ oder _Zonal Standard Persistent Disks_ sein.
+
--
Persistente SSD-Festplatten eignen sich ideal für Workloads, die eine hohe Anzahl von zufälligen IOPS erfordern, während Standard-persistente Festplatten wirtschaftlich sind und sequenzielle Lese-/Schreibvorgänge verarbeiten können. Weitere Informationen finden Sie unter https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud-Dokumentation: Zonal Persistent Disks (Standard und SSD)"^].

--
GCP-Festplattengröße:: Sie müssen bei der Implementierung eines Cloud Volumes ONTAP Systems die ursprüngliche Festplattengröße auswählen. Danach können Sie mit Cloud Manager die Kapazität eines Systems für Sie verwalten. Wenn Sie jedoch die Aggregate selbst erstellen möchten, beachten Sie Folgendes:
+
--
* Alle Festplatten in einem Aggregat müssen dieselbe Größe haben.
* Ermitteln Sie den Speicherplatz, den Sie benötigen, während Sie gleichzeitig die Performance in Betracht ziehen.
* Die Performance persistenter Festplatten lässt sich automatisch mit der Festplattengröße und der Anzahl der für das System verfügbaren vCPUs skalieren.
+
Weitere Informationen finden Sie im Folgenden:

+
** https://cloud.google.com/compute/docs/disks/#pdspecs["Google Cloud-Dokumentation: Zonal Persistent Disks (Standard und SSD)"^]
** https://cloud.google.com/compute/docs/disks/performance["Google Cloud-Dokumentation: Optimierung von Persistent Disk und lokaler SSD-Performance"^]




--




=== Informationarbeitsblatt für das GCP-Netzwerk

Bei der Implementierung von Cloud Volumes ONTAP in GCP müssen Details zu Ihrem virtuellen Netzwerk angegeben werden. Sie können ein Arbeitsblatt verwenden, um die Informationen von Ihrem Administrator zu sammeln.

[cols="30,70"]
|===
| GCP-Informationen | Ihr Wert 


| Region |  


| Zone |  


| VPC-Netzwerk |  


| Subnetz |  


| Firewallrichtlinie (bei Nutzung eigener Richtlinien) |  
|===